version: '3.8'

networks:
  net:
    name: rpa-network
    external: true

services:
  rpa:
    build: .
    volumes:
      - /opt/app/BuildTarget/DZT/Oscillogram:/opt/app/BuildTarget/DZT/Oscillogram
    networks:
      net:
        ipv4_address: 192.168.5.100