version: '3.8'

networks:
  net:
    name: rpa-network
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
      driver_opts:
        com.docker.network.bridge.name: br_test

services:
  rpa:
    build: .
    volumes:
      - /opt/app/BuildTarget/DZT/Oscillogram:/opt/app/BuildTarget/DZT/Oscillogram
    networks:
      net:
        ipv4_address: 192.168.5.100